"""empty message

Revision ID: 121a105254e2
Revises:
Create Date: 2022-01-20 08:53:30.177600

"""
import csv

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121a105254e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('installs', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_channel'), 'metrics', ['channel'], unique=False)
    op.create_index(op.f('ix_metrics_country'), 'metrics', ['country'], unique=False)
    op.create_index(op.f('ix_metrics_date'), 'metrics', ['date'], unique=False)
    op.create_index(op.f('ix_metrics_os'), 'metrics', ['os'], unique=False)

    con = op.get_bind()
    with open(f'migrations/data/dataset.csv', newline='') as csvfile:
        checklist = list(csv.reader(csvfile, delimiter=','))
    stmt = sa.text("""INSERT INTO metrics(date, channel, country, os, impressions, clicks, installs, spend, revenue) VALUES (?,?,?,?,?,?,?,?,?)""")
    con.connection.executemany(str(stmt), checklist[1:])


def downgrade():
    op.drop_index(op.f('ix_metrics_os'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_date'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_country'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_channel'), table_name='metrics')
    op.drop_table('metrics')
